# Generated by Django 5.1.4 on 2024-12-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantHotelEvent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room_type',
        ),
    ]
